spring:
  application:
    name: Property Management
  datasource:
    url: jdbc:postgresql://localhost:54321/property-mgmt
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
